language: cpp
sudo: false
dist: trusty
python: 2.7
virtualenv:
    system_site_packages: true 

compiler:
  - clang
  - gcc
env:
  - CONFIG_OPTIONS="--without-x --without-paranrn --with-nrnpython=$(which python2)"
  - CONFIG_OPTIONS="--without-x --without-paranrn --with-nrnpython=$(which python3)"
os:
  - linux
before_install:
  - echo $LANG
  - echo $LC_ALL
  - $CXX -v
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/install/lib/python/
install:
  - pip install numpy 
  - pip install scipy
  - pip install matplotlib
script:
  - ./travis_build.sh .
  - echo $PYTHONPATH
  - ls ./install/lib/python/
  - python share/lib/python/neuron/rxdtests/run_all.py
